export const TELEGRAM_HELP = [
  '🧭 **Nexus — aide**',
  'Pilotez le projet ouvert dans VS Code depuis cette conversation.',
  '',
  '🤖 **Travailler avec Codex**',
  '`/codex <instruction>` — Envoyer une demande à Codex.',
  '`/stop` — Demander l’arrêt de la requête Codex en cours.',
  '`/model` — Choisir le modèle et son effort de raisonnement avec les boutons.',
  'Le choix est conservé pour ce workspace et s’applique au prochain prompt.',
  '',
  '💬 **Gérer les sessions**',
  '`/new` — Créer une nouvelle conversation dans le projet courant.',
  '`/resume <id>` — Reprendre une conversation existante dans ce projet.',
  'Retrouvez l’identifiant de la session sélectionnée avec /status.',
  '',
  '🌿 **Choisir une branche**',
  '`/branches` — Lister les branches et repérer la branche courante.',
  '`/switch <branche>` — Passer sur la branche choisie.',
  'Exemple local : `/switch staging`',
  'Exemple distant : `/switch origin/staging` crée la branche locale avec suivi distant.',
  'Après un changement de branche, utilisez /new ou /resume <id> si une session était déjà sélectionnée.',
  '',
  '📡 **État et connexion**',
  '`/status` — Afficher le projet, le modèle, l’activité, les tokens et les quotas Codex.',
  '`/ping` — Vérifier la connexion ; Nexus répond « pong ».',
  '`/help` — Afficher cette aide.',
  '`/pair <code>` — Appairer Telegram avec le code fourni par **Nexus: Pair Telegram** dans VS Code.',
  '',
  '✍️ **Exemple de demande**',
  '`/codex Explique le rôle de ce projet sans modifier les fichiers.`',
  '',
  'Les paramètres entre <…> sont à remplacer par vos valeurs, sans les chevrons.',
].join('\n');
